### ISSUE TITLE
error when compiling with webpack

### ISSUE THREAD

**Issue by HenrryPires** [Bogdan1975/ng2-slider-component#30]
Hi

when i use webpack i get the following error

ERROR in ./~ /ng2-slider-component/ng2-slider.component.html
Module parse failed: <filder>\node_modules\ng2-slider-component\ng2-slider.component.html Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:0)
    at Parser.pp$4.raise (<filder>\node_modules\webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (<filder>\node_modules\webpack\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (<filder>\node_modules\webpack\node_modules\acorn\dist\acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (<filder>\node_modules\webpack\node_modules\acorn\dist\acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (<filder>\node_modules\webpack\node_modules\acorn\dist\acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (<filder>\node_modules\webpack\node_modules\acorn\dist\acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (<filder>\node_modules\webpack\node_modules\acorn\dist\acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (<filder>\node_modules\webpack\node_modules\acorn\dist\acorn.js:1597:21)
    at Parser.pp$3.parseExpression (<filder>\node_modules\webpack\node_modules\acorn\dist\acorn.js:1573:21)
    at Parser.pp$1.parseStatement (<filder>\node_modules\webpack\node_modules\acorn\dist\acorn.js:727:47)
 @ ./~/ng2-slider-component/ng2-slider.component.js 402:22-60

anyone else with the same problem?

**Comment by martinmanzo** [comment]
Hi @HenrryPires, could you fix this?
